package com.kingyee.ibatis.model;

public class CmsAdmin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.userid
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.username
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.allowmultilogin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	private Boolean allowmultilogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.alloweditpassword
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	private Boolean alloweditpassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.editpasswordnextlogin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	private Boolean editpasswordnextlogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_admin.disabled
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	private Boolean disabled;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.userid
	 * @return  the value of cms_admin.userid
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.userid
	 * @param userid  the value for cms_admin.userid
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.username
	 * @return  the value of cms_admin.username
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.username
	 * @param username  the value for cms_admin.username
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.allowmultilogin
	 * @return  the value of cms_admin.allowmultilogin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public Boolean getAllowmultilogin() {
		return allowmultilogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.allowmultilogin
	 * @param allowmultilogin  the value for cms_admin.allowmultilogin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public void setAllowmultilogin(Boolean allowmultilogin) {
		this.allowmultilogin = allowmultilogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.alloweditpassword
	 * @return  the value of cms_admin.alloweditpassword
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public Boolean getAlloweditpassword() {
		return alloweditpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.alloweditpassword
	 * @param alloweditpassword  the value for cms_admin.alloweditpassword
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public void setAlloweditpassword(Boolean alloweditpassword) {
		this.alloweditpassword = alloweditpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.editpasswordnextlogin
	 * @return  the value of cms_admin.editpasswordnextlogin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public Boolean getEditpasswordnextlogin() {
		return editpasswordnextlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.editpasswordnextlogin
	 * @param editpasswordnextlogin  the value for cms_admin.editpasswordnextlogin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public void setEditpasswordnextlogin(Boolean editpasswordnextlogin) {
		this.editpasswordnextlogin = editpasswordnextlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_admin.disabled
	 * @return  the value of cms_admin.disabled
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public Boolean getDisabled() {
		return disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_admin.disabled
	 * @param disabled  the value for cms_admin.disabled
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}
}