package com.kingyee.ibatis.mapper;

import com.kingyee.ibatis.model.CmsAdmin;
import com.kingyee.ibatis.model.CmsAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsAdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int countByExample(CmsAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int deleteByExample(CmsAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int insert(CmsAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int insertSelective(CmsAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	List<CmsAdmin> selectByExample(CmsAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	CmsAdmin selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int updateByExampleSelective(@Param("record") CmsAdmin record,
			@Param("example") CmsAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int updateByExample(@Param("record") CmsAdmin record,
			@Param("example") CmsAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int updateByPrimaryKeySelective(CmsAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_admin
	 * @mbggenerated  Sun Jan 26 16:55:55 CST 2014
	 */
	int updateByPrimaryKey(CmsAdmin record);
}